[tool.poetry]
name = "hm-products-sales"
version = "0.1.0"
description = ""
authors = ["maks_kras <maksym_krasovskiy@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.32.5"
mypy = ">=1.18.2"
black = ">=25.11.0"
isort = ">=7.0.0"
flake8 = ">=7.3.0"
poetry-core = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
    "mypy (>=1.18.2,<2.0.0)",
    "black (>=25.11.0,<26.0.0)",
    "isort (>=7.0.0,<8.0.0)",
    "flake8 (>=7.3.0,<8.0.0)"
]
dev = [
    "requests (>=2.32.5,<3.0.0)"
]

[tool.mypy]
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
exclude = 'venv'

[tool.black]
line-length = 119
exclude = '''
(
    \(
        |\.git
    )\
)
'''

[tool.isort]
line_length = 119
